name: Lint and test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    env:
      VFLAGS: '-path "../|@vlib"'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup V
        run: |
          git clone --depth=1 https://github.com/vlang/v /tmp/v && cd /tmp/v && make
          /tmp/v/v symlink

      - name: Run tests
        run: |
          v fmt -verify .
          v vet -v -W -I -F -r .
          v missdoc -r --verify .
          v test .

  test-windows:
    runs-on: windows-latest
    env:
      VFLAGS: '-path "../|@vlib" -cc gcc'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup V
        shell: bash
        run: |
          mkdir D:\Temp
          git clone --depth=1 https://github.com/vlang/v D:\Temp\v && cd D:\Temp\v && ./makev.bat -gcc
          echo D:\Temp\v >> $GITHUB_PATH
          v version

      - name: Run tests
        shell: bash
        run: |
          v fmt -verify .
          v vet -v -W -I -F -r .
          v test .
